(define (anagram string1 string2)
  (define (anacurry s1 s2)
    (if (null? s1)
        (begin
          (display string1)
          (display " is an anagram of ")
          (display string2)
          )
        (if (member (car s1) s2)
            (anacurry (cdr s1) s2) 
            (begin
              (display string1)
              (display " is not an anagram of ")
              (display string2)
              )
            )
        )
    )
  (if (eq? (length (string->list string1)) (length (string->list string2)))
      (anacurry (string->list string1) (string->list string2))
      (begin
        (display string1)
        (display " is not an anagram of ")
        (display string2)
        )
      )
  )

(anagram "soumynona" "anonymous")